.TH legion 1 "30th Nov 2017" v1
.SH NAME
legion - scriptable access to remote servers via SSH

.SH SYNOPSIS
Legion is a tool that allows a simple scripting language (with a mini template system) 
to run over SSH to a target system. The scripting language can issue commands, copy 
files from the host to the target and upload and execute stored scripts

.SH DESCRIPTION
.B Prerequisites

Legion requires Ruby 1.9.3 or better because it currently uses the colorize gem. I will probably just steal the parts of colorize I require at some point so that even 1.8.7 can use legion

So you need to colorize gem

gem install colorize

.SH OPTIONS
.TP
.B --host
.I required
The name of the host to connect to
.TP
.B --port
.I optional
The port to connect to the host on, defaults to 22
.TP
.B --username
.I required
The username to connect to the host with
.TP
.B --password
.I required
The password that goes with the username, even when using ssh key exchange there needs to be a value for this, dummy would be fine
.TP
.B --pretend
.I optional
Takes no argument. Runs the script but does not actually make the ssh and sftp connections and fakes the interaction
.TP
.B --set
.I optional
Takes two arguments and acts like the set command within a legion script
.TP
.B --log
.I optional
Sets the log file name to whatever is given as the parameter. By default the log file will be called 
.BI legion.YYYYMMDD-HHMM.log
.TP
.B --config
.I optional
An optional config file to save having really long command lines

.SH BUGS
None

.SH AUTHOR
Peter Hickman <peterhickman386@googlemail.com>

.SH SEE ALSO
Have you tried looking behind the sofa?
