#!/usr/bin/env ruby
# encoding: UTF-8
# frozen_string_literal: true

require 'rubygems'
require 'net/ssh'
require 'net/sftp'

class String
  ##
  # Normal colours
  ##
  def black
    colorize(30)
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end

  def yellow
    colorize(33)
  end

  def blue
    colorize(34)
  end

  def magenta
    colorize(35)
  end

  def cyan
    colorize(36)
  end

  def white
    colorize(37)
  end

  ##
  # Bright colours
  ##
  def bright_black
    colorize(90)
  end

  def bright_red
    colorize(91)
  end

  def bright_green
    colorize(92)
  end

  def bright_yellow
    colorize(93)
  end

  def bright_blue
    colorize(94)
  end

  def bright_magenta
    colorize(95)
  end

  def bright_cyan
    colorize(96)
  end

  def bright_white
    colorize(97)
  end

  ##
  # Normal background colours
  ##
  def bg_black
    colorize(40)
  end

  def bg_red
    colorize(41)
  end

  def bg_green
    colorize(42)
  end

  def bg_yellow
    colorize(43)
  end

  def bg_blue
    colorize(44)
  end

  def bg_magenta
    colorize(45)
  end

  def bg_cyan
    colorize(46)
  end

  def bg_white
    colorize(47)
  end

  ##
  # Bright background colours
  ##
  def bg_bright_black
    colorize(100)
  end

  def bg_bright_red
    colorize(101)
  end

  def bg_bright_green
    colorize(102)
  end

  def bg_bright_yellow
    colorize(103)
  end

  def bg_bright_blue
    colorize(104)
  end

  def bg_bright_magenta
    colorize(105)
  end

  def bg_bright_cyan
    colorize(106)
  end

  def bg_bright_white
    colorize(107)
  end

  private

  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end
end

class Legion
  def initialize(list)
    @script_files = []
    @options = {}

    list.each do |filename|
      if File.exist?(filename)
        @script_files << filename
      else
        dropdead "[#{filename}] is not a real file"
      end
    end

    Dir.mkdir('log') unless File.directory?('log')

    logfile_name = "log/legion.#{Time.now.strftime('%Y%m%d-%H%M')}.log"
    @logger = File.open(logfile_name, 'w')

    log '#', "Log file written to #{logfile_name}"

    @ssh  = nil
    @sftp = nil
  end

  def process
    log '#', "Legion command line #{@script_files.join(' ')}"

    @script_files.each do |script_file|
      process_file(script_file)
    end

    log '#', 'Done'
  end

  private

  def log(connection, message)
    text = "#{Time.now.strftime('%Y-%m-%d %H:%M:%S.%6N')} #{connection}"

    @logger.puts "#{text} #{message}" if @logger

    message = case connection
              when ':'
                message.green
              when '>'
                message.blue
              when '!'
                message.red
              when '#'
                message.yellow
              else
                message
              end

    puts "#{text} #{message}"
  end

  def make_connections
    return unless @ssh.nil?

    check_options

    @ssh = connect_ssh
    @sftp = connect_sftp
  end

  def connect_ssh
    log ':', 'Establishing ssh connection'

    begin
      ssh = Net::SSH.start(@options['host'], @options['username'], password: @options['password'], port: @options['port'])
    rescue StandardError => e
      dropdead "Failed to open ssh connection: #{e}"
    end

    ssh
  end

  def connect_sftp
    log ':', 'Establishing sftp connection'

    begin
      sftp = Net::SFTP.start(@options['host'], @options['username'], password: @options['password'], port: @options['port'])
    rescue StandardError => e
      dropdead "Failed to open sftp connection: #{e}"
    end

    sftp
  end

  def check_options
    %w[host port username password].each do |k|
      next if @options.key?(k)

      dropdead "Missing key [#{k}]"
    end
  end

  def interpolate(text)
    line = text.dup

    while line.include?('{{')
      line =~ /({{([^}]+)}})/

      t = $1.to_s
      k = $2.downcase

      if @options.key?(k)
        line = line.gsub(t, @options[k])
      else
        dropdead "Unable to substitute #{t}, #{k} not set in [#{text}]"
      end
    end

    line
  end

  def do_cmd(command)
    command = interpolate(command)

    log '>', "CMD #{command}"

    make_connections

    begin
      @ssh.exec!(command) do |_, stream, data|
        if stream == :stdout
          data.split("\n").each do |line|
            log '<', line
          end
        elsif stream == :stderr
          data.split("\n").each do |line|
            log '!', line
          end
        end
      end
    rescue StandardError => e
      if command.include?('reboot')
        # Yeah, the reboot command will cut the connection
        # We're expecting that so we'll let it slide
      else
        log '!', "Exception: #{e}"
        e.backtrace.each { |line| log ':', line }
      end
    end
  end

  def do_copy(text)
    text = interpolate(text)

    from, to = text.split(/\s+/)

    log '>', "COPY [#{from}] to [#{to}]"

    make_connections

    begin
      @sftp.upload!(from, to)
    rescue StandardError => e
      dropdead "Unable to copy file: #{e}"
    end
  end

  def do_config(text)
    k, v = text.split(/\s+/, 2)
    k = k.downcase
    @options[k] = v
  end

  def do_echo(text)
    log '#', interpolate(text)
  end

  def do_debug
    log '#', 'START CONFIG'
    @options.each do |k, v|
      log '#', "[#{k}] = [#{v}]"
    end
  end

  def do_include(filename)
    if File.exist?(filename)
      process_file(filename)
    else
      dropdead "Include file #{filename} not found"
    end
  end

  def dropdead(message)
    log '!', message
    exit
  end

  def process_file(filename)
    log '#', "Reading commands from #{filename}"

    line_number = 0

    File.open(filename, 'r').each do |line|
      line_number += 1

      next if line =~ /^\s*$/
      next if line =~ /^\s*\#/

      c, v = line.chomp.strip.split(/\s+/, 2)

      case c.upcase
      when 'CMD'
        do_cmd(v)
      when 'COPY'
        do_copy(v)
      when 'CONFIG'
        do_config(v)
      when 'ECHO'
        do_echo(v)
      when 'DEBUG'
        do_debug
      when 'HALT'
        dropdead "#{filename} commits suicide at line #{line_number}"
      when 'INCLUDE'
        do_include(v)
      else
        dropdead "Unknown command [#{c}] at line #{line_number} of #{filename}"
      end
    end

    log '#', "Completed #{filename}"
  end
end

l = Legion.new(ARGV)
l.process
