production:
    adapter:   postgresql
    host:      localhost
    username:  APPLICATION_NAME
    database:  APPLICATION_NAME_production
test:
    adapter:   postgresql
    host:      localhost
    username:  APPLICATION_NAME
    database:  APPLICATION_NAME_test
development:
    adapter:   postgresql
    host:      localhost
    username:  APPLICATION_NAME
    database:  APPLICATION_NAME_development
