<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>legion</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Legion</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(CMD|COPY|CONFIG|ECHO|DEBUG|HALT|INCLUDE)\b</string>

			<key>name</key>
			<string>keyword.control.legion</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.legion</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.legion</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.legion</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.legion</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>markup.bold.legion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.legion</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.legion</string>
	<key>uuid</key>
	<string>CE154A9B-197B-422C-8809-E1036EA2C88F</string>
</dict>
</plist>
